package com.verto.modules.pipeline.service.impl;

import com.verto.modules.pipeline.dto.PipelineCreateRequest;
import com.verto.modules.pipeline.service.IJenkinsService;
import com.verto.modules.pipeline.service.JenkinsProperties;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.*;
import org.springframework.stereotype.Service;
import org.springframework.util.StringUtils;
import org.springframework.web.client.HttpClientErrorException;
import org.springframework.web.client.RestTemplate;
import org.springframework.web.util.UriComponentsBuilder;

import java.nio.charset.StandardCharsets;
import java.util.Base64;
import java.util.HashMap;
import java.util.Map;

@Service
@Slf4j
public class JenkinsServiceImpl implements IJenkinsService {

    @Autowired
    private JenkinsProperties jenkinsProperties;

    private RestTemplate restTemplate = new RestTemplate();

    private HttpHeaders buildAuthHeaders() {
        String auth = jenkinsProperties.getUser() + ":" + jenkinsProperties.getToken();
        String encodedAuth = Base64.getEncoder().encodeToString(auth.getBytes(StandardCharsets.UTF_8));
        HttpHeaders headers = new HttpHeaders();
        headers.set("Authorization", "Basic " + encodedAuth);
        headers.setContentType(MediaType.APPLICATION_XML);
        return headers;
    }

    private Map<String, String> getCrumb() {
        try {
            String url = jenkinsProperties.getUrl() + "/crumbIssuer/api/json";
            HttpEntity<Void> entity = new HttpEntity<>(buildAuthHeaders());
            ResponseEntity<Map> resp = restTemplate.exchange(url, HttpMethod.GET, entity, Map.class);
            Map<String, String> result = new HashMap<>();
            if (resp.getStatusCode().is2xxSuccessful() && resp.getBody() != null) {
                Object field = resp.getBody().get("crumbRequestField");
                Object crumb = resp.getBody().get("crumb");
                if (field != null && crumb != null) {
                    result.put("field", field.toString());
                    result.put("crumb", crumb.toString());
                }
            }
            return result;
        } catch (Exception e) {
            log.warn("Failed to fetch Jenkins crumb, CSRF may be disabled: {}", e.getMessage());
            return new HashMap<>();
        }
    }

    private boolean jobExists(String jobName) {
        try {
            String url = jenkinsProperties.getUrl() + "/job/" + jobName + "/config.xml";
            HttpEntity<Void> entity = new HttpEntity<>(buildAuthHeaders());
            ResponseEntity<String> resp = restTemplate.exchange(url, HttpMethod.GET, entity, String.class);
            return resp.getStatusCode().is2xxSuccessful();
        } catch (HttpClientErrorException.NotFound e) {
            return false;
        } catch (Exception e) {
            log.error("Check job exists error: {}", e.getMessage());
            return false;
        }
    }

    private String buildConfigXml(PipelineCreateRequest req) {
        if (req.isUseInlineScript() && StringUtils.hasText(req.getPipelineScript())) {
            String scriptEscaped = req.getPipelineScript()
                    .replace("&", "&amp;")
                    .replace("<", "&lt;")
                    .replace(">", "&gt;");
            return "" +
                    "<?xml version=\"1.1\" encoding=\"UTF-8\"?>\n" +
                    "<flow-definition plugin=\"workflow-job\">\n" +
                    "  <description>Generated by Verto</description>\n" +
                    "  <keepDependencies>false</keepDependencies>\n" +
                    "  <definition class=\"org.jenkinsci.plugins.workflow.cps.CpsFlowDefinition\" plugin=\"workflow-cps\">\n" +
                    "    <script>" + scriptEscaped + "</script>\n" +
                    "    <sandbox>true</sandbox>\n" +
                    "  </definition>\n" +
                    "  <triggers/>\n" +
                    "  <disabled>false</disabled>\n" +
                    "</flow-definition>\n";
        }

        // Default: use SCM Jenkinsfile
        String repoUrl = req.getRepoUrl();
        String branch = StringUtils.hasText(req.getBranch()) ? req.getBranch() : "*/main";
        String credentialsId = req.getCredentialsId();
        String scriptPath = StringUtils.hasText(req.getJenkinsfilePath()) ? req.getJenkinsfilePath() : "Jenkinsfile";

        return "" +
                "<?xml version=\"1.1\" encoding=\"UTF-8\"?>\n" +
                "<flow-definition plugin=\"workflow-job\">\n" +
                "  <description>Generated by Verto</description>\n" +
                "  <keepDependencies>false</keepDependencies>\n" +
                "  <definition class=\"org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition\" plugin=\"workflow-cps\">\n" +
                "    <scm class=\"hudson.plugins.git.GitSCM\" plugin=\"git\">\n" +
                "      <configVersion>2</configVersion>\n" +
                "      <userRemoteConfigs>\n" +
                "        <hudson.plugins.git.UserRemoteConfig>\n" +
                "          <url>" + repoUrl + "</url>\n" +
                (StringUtils.hasText(credentialsId) ? "          <credentialsId>" + credentialsId + "</credentialsId>\n" : "") +
                "        </hudson.plugins.git.UserRemoteConfig>\n" +
                "      </userRemoteConfigs>\n" +
                "      <branches>\n" +
                "        <hudson.plugins.git.BranchSpec>\n" +
                "          <name>" + branch + "</name>\n" +
                "        </hudson.plugins.git.BranchSpec>\n" +
                "      </branches>\n" +
                "      <doGenerateSubmoduleConfigurations>false</doGenerateSubmoduleConfigurations>\n" +
                "      <submoduleCfg class=\"list\"/>\n" +
                "      <extensions/>\n" +
                "    </scm>\n" +
                "    <scriptPath>" + scriptPath + "</scriptPath>\n" +
                "    <lightweight>true</lightweight>\n" +
                "  </definition>\n" +
                "  <triggers/>\n" +
                "  <disabled>false</disabled>\n" +
                "</flow-definition>\n";
    }

    @Override
    public Map<String, Object> createOrUpdatePipelineJob(PipelineCreateRequest request) {
        Map<String, Object> result = new HashMap<>();
        String jobName = request.getJobName();
        String configXml = buildConfigXml(request);

        // Prepare headers with auth and crumb
        HttpHeaders headers = buildAuthHeaders();
        Map<String, String> crumb = getCrumb();
        if (crumb.containsKey("field") && crumb.containsKey("crumb")) {
            headers.set(crumb.get("field"), crumb.get("crumb"));
        }

        HttpEntity<String> entity = new HttpEntity<>(configXml, headers);

        try {
            if (jobExists(jobName)) {
                // Update existing job
                String url = jenkinsProperties.getUrl() + "/job/" + jobName + "/config.xml";
                ResponseEntity<String> resp = restTemplate.exchange(url, HttpMethod.POST, entity, String.class);
                result.put("action", "updated");
                result.put("status", resp.getStatusCodeValue());
                result.put("jobUrl", jenkinsProperties.getUrl() + "/job/" + jobName + "/");
            } else {
                // Create new job
                String url = UriComponentsBuilder.fromHttpUrl(jenkinsProperties.getUrl() + "/createItem")
                        .queryParam("name", jobName)
                        .toUriString();
                ResponseEntity<String> resp = restTemplate.exchange(url, HttpMethod.POST, entity, String.class);
                result.put("action", "created");
                result.put("status", resp.getStatusCodeValue());
                result.put("jobUrl", jenkinsProperties.getUrl() + "/job/" + jobName + "/");
            }
        } catch (Exception e) {
            log.error("Failed to create/update Jenkins job: {}", e.getMessage());
            result.put("error", e.getMessage());
        }

        return result;
    }
}