version: '3.8'

services:
  # Jenkins 服务
  jenkins:
    image: jenkins/jenkins:2.276
    container_name: verto-jenkins
    hostname: jenkins.local
    restart: unless-stopped
    user: root
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_OPTS=--httpPort=8803
    ports:
      - '8803:8803'    # Jenkins Web界面
      - '8804:50000'  # Jenkins Agent端口
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_docker:/usr/bin/docker
    networks:
      - devops-network
    depends_on:
      - gitlab



  # PostgreSQL (用于GitLab数据库，可选，GitLab默认使用内置PostgreSQL)
  postgres:
    image: postgres:13
    container_name: verto-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: gitlabhq_production
      POSTGRES_USER: gitlab
      POSTGRES_PASSWORD: gitlab_password
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - devops-network

# 数据卷定义
volumes:
  # GitLab 数据卷
  gitlab_config:
    driver: local
  gitlab_logs:
    driver: local
  gitlab_data:
    driver: local
  
  # Jenkins 数据卷
  jenkins_home:
    driver: local
  jenkins_docker:
    driver: local
  jenkins_agent_workdir:
    driver: local
  
  # 数据库和缓存数据卷
  postgres_data:
    driver: local
  redis_data:
    driver: local

# 网络定义
networks:
  devops-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16